-- ============================================================
-- rental-crm 스키마 DDL
-- 컨테이너 최초 부팅 시 자동 실행 (/container-entrypoint-initdb.d/)
--
-- 전제: APP_USER=rental 이 docker-compose 환경변수로 사전 생성됨
-- 모든 객체는 rental 스키마에 생성
-- ============================================================

ALTER SESSION SET CURRENT_SCHEMA = rental;

-- ============================================================
-- 1. 시퀀스 (테이블별 1:1, allocationSize=50 호환)
-- ============================================================
CREATE SEQUENCE SEQ_CM_CODE          START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_ROLE          START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_MENU          START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_ROLE_MENU     START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_USER          START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_NOTIFICATION  START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CT_CUSTOMER      START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CT_EQUIPMENT     START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CT_PRODUCT       START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CT_CONTRACT      START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CT_ENGINEER      START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CT_VISIT         START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_BL_BILLING       START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BL_PAYMENT       START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BL_OVERDUE       START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BL_BATCH_LOG     START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

-- ============================================================
-- 2. 공통 (CM_*) 테이블
-- ============================================================

-- 2-1. 공통코드 그룹
CREATE TABLE CM_CODE_GROUP (
    GROUP_CODE          VARCHAR2(50)   NOT NULL,
    GROUP_NAME          VARCHAR2(100)  NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    USE_YN              VARCHAR2(1)        DEFAULT 'Y' NOT NULL,
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CM_CODE_GROUP PRIMARY KEY (GROUP_CODE)
);

-- 2-2. 공통코드
CREATE TABLE CM_CODE (
    CODE_ID             NUMBER         NOT NULL,
    GROUP_CODE          VARCHAR2(50)   NOT NULL,
    CODE_VALUE          VARCHAR2(50)   NOT NULL,
    CODE_NAME           VARCHAR2(100)  NOT NULL,
    SORT_ORDER          NUMBER         DEFAULT 0 NOT NULL,
    USE_YN              VARCHAR2(1)        DEFAULT 'Y' NOT NULL,
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CM_CODE PRIMARY KEY (CODE_ID),
    CONSTRAINT UK_CM_CODE_GROUP_VALUE UNIQUE (GROUP_CODE, CODE_VALUE),
    CONSTRAINT FK_CM_CODE_GROUP FOREIGN KEY (GROUP_CODE) REFERENCES CM_CODE_GROUP (GROUP_CODE)
);

-- 2-3. 권한/역할
CREATE TABLE CM_ROLE (
    ROLE_ID             NUMBER         NOT NULL,
    ROLE_CODE           VARCHAR2(50)   NOT NULL,
    ROLE_NAME           VARCHAR2(100)  NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    USE_YN              VARCHAR2(1)        DEFAULT 'Y' NOT NULL,
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CM_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT UK_CM_ROLE_CODE UNIQUE (ROLE_CODE)
);

-- 2-4. 메뉴
CREATE TABLE CM_MENU (
    MENU_ID             NUMBER         NOT NULL,
    PARENT_MENU_ID      NUMBER,
    MENU_DEPTH          NUMBER         NOT NULL,
    MENU_NAME           VARCHAR2(100)  NOT NULL,
    MENU_TYPE           VARCHAR2(20)   NOT NULL,
    MENU_URL            VARCHAR2(200),
    ICON_CLASS          VARCHAR2(50),
    SORT_ORDER          NUMBER         DEFAULT 0 NOT NULL,
    USE_YN              VARCHAR2(1)        DEFAULT 'Y' NOT NULL,
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CM_MENU PRIMARY KEY (MENU_ID),
    CONSTRAINT FK_CM_MENU_PARENT FOREIGN KEY (PARENT_MENU_ID) REFERENCES CM_MENU (MENU_ID),
    CONSTRAINT CK_CM_MENU_TYPE CHECK (MENU_TYPE IN ('GROUP', 'LEAF'))
);

-- 2-5. 역할-메뉴 권한
CREATE TABLE CM_ROLE_MENU (
    ROLE_MENU_ID        NUMBER         NOT NULL,
    ROLE_ID             NUMBER         NOT NULL,
    MENU_ID             NUMBER         NOT NULL,
    READ_YN             VARCHAR2(1)        DEFAULT 'N' NOT NULL,
    WRITE_YN            VARCHAR2(1)        DEFAULT 'N' NOT NULL,
    DELETE_YN           VARCHAR2(1)        DEFAULT 'N' NOT NULL,
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CM_ROLE_MENU PRIMARY KEY (ROLE_MENU_ID),
    CONSTRAINT UK_CM_ROLE_MENU UNIQUE (ROLE_ID, MENU_ID),
    CONSTRAINT FK_CM_ROLE_MENU_ROLE FOREIGN KEY (ROLE_ID) REFERENCES CM_ROLE (ROLE_ID),
    CONSTRAINT FK_CM_ROLE_MENU_MENU FOREIGN KEY (MENU_ID) REFERENCES CM_MENU (MENU_ID)
);

-- 2-6. 관리자 계정
CREATE TABLE CM_USER (
    USER_ID             NUMBER         NOT NULL,
    EMAIL               VARCHAR2(254)  NOT NULL,
    PASSWORD            VARCHAR2(255)  NOT NULL,
    USER_NAME           VARCHAR2(100)  NOT NULL,
    PHONE               VARCHAR2(20),
    ROLE_ID             NUMBER,
    USE_YN              VARCHAR2(1)        DEFAULT 'Y' NOT NULL,
    LOGIN_FAIL_CNT      NUMBER         DEFAULT 0 NOT NULL,
    LOCKED_AT           TIMESTAMP(0),
    LAST_LOGIN_AT       TIMESTAMP(0),
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CM_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_CM_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_CM_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES CM_ROLE (ROLE_ID)
);

-- 2-7. 알림
CREATE TABLE CM_NOTIFICATION (
    NOTIFICATION_ID     NUMBER         NOT NULL,
    RECIPIENT_USER_ID   NUMBER,
    NOTIFICATION_TYPE   VARCHAR2(50)   NOT NULL,
    MESSAGE             VARCHAR2(1000) NOT NULL,
    REF_TYPE            VARCHAR2(50),
    REF_ID              NUMBER,
    READ_YN             VARCHAR2(1)        DEFAULT 'N' NOT NULL,
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CM_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID),
    CONSTRAINT FK_CM_NOTIFICATION_USER FOREIGN KEY (RECIPIENT_USER_ID) REFERENCES CM_USER (USER_ID)
);

-- ============================================================
-- 3. 계약/장비 (CT_*) 테이블
-- ============================================================

-- 3-1. 고객
CREATE TABLE CT_CUSTOMER (
    CUSTOMER_ID         NUMBER         NOT NULL,
    CUSTOMER_NO         VARCHAR2(20)   NOT NULL,
    CUSTOMER_NAME       VARCHAR2(100)  NOT NULL,
    EMAIL               VARCHAR2(254)  NOT NULL,
    PASSWORD            VARCHAR2(255)  NOT NULL,
    PHONE               VARCHAR2(20)   NOT NULL,
    BIRTH_DATE          DATE,
    ADDRESS_ZIP         VARCHAR2(10),
    ADDRESS             VARCHAR2(500)  NOT NULL,
    TERMS_AGREE_YN      VARCHAR2(1)        NOT NULL,
    USE_YN              VARCHAR2(1)        DEFAULT 'Y' NOT NULL,
    LOGIN_FAIL_CNT      NUMBER         DEFAULT 0 NOT NULL,
    LOCKED_AT           TIMESTAMP(0),
    LAST_LOGIN_AT       TIMESTAMP(0),
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CT_CUSTOMER PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UK_CT_CUSTOMER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_CT_CUSTOMER_NO UNIQUE (CUSTOMER_NO),
    CONSTRAINT CK_CT_CUSTOMER_TERMS CHECK (TERMS_AGREE_YN IN ('Y', 'N'))
);

-- 3-2. 장비
CREATE TABLE CT_EQUIPMENT (
    EQUIPMENT_ID        NUMBER         NOT NULL,
    EQUIPMENT_CODE      VARCHAR2(20)   NOT NULL,
    EQUIPMENT_TYPE      VARCHAR2(50)   NOT NULL,
    MODEL_NAME          VARCHAR2(200)  NOT NULL,
    MANUFACTURER        VARCHAR2(200)  NOT NULL,
    RELEASE_DATE        DATE,
    IMAGE_URL           VARCHAR2(500),
    DESCRIPTION         VARCHAR2(1000),
    USE_YN              VARCHAR2(1)        DEFAULT 'Y' NOT NULL,
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CT_EQUIPMENT PRIMARY KEY (EQUIPMENT_ID),
    CONSTRAINT UK_CT_EQUIPMENT_MODEL UNIQUE (MODEL_NAME, MANUFACTURER),
    CONSTRAINT UK_CT_EQUIPMENT_CODE UNIQUE (EQUIPMENT_CODE)
);

-- 3-3. 상품
CREATE TABLE CT_PRODUCT (
    PRODUCT_ID          NUMBER         NOT NULL,
    PRODUCT_CODE        VARCHAR2(20)   NOT NULL,
    EQUIPMENT_ID        NUMBER         NOT NULL,
    PRODUCT_NAME        VARCHAR2(200)  NOT NULL,
    MONTHLY_FEE         NUMBER         NOT NULL,
    CONTRACT_MONTHS     NUMBER         NOT NULL,
    DEPOSIT_AMOUNT      NUMBER         DEFAULT 0 NOT NULL,
    INSTALL_FEE         NUMBER         DEFAULT 0 NOT NULL,
    DESCRIPTION         VARCHAR2(1000),
    USE_YN              VARCHAR2(1)        DEFAULT 'Y' NOT NULL,
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CT_PRODUCT PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT UK_CT_PRODUCT_CODE UNIQUE (PRODUCT_CODE),
    CONSTRAINT FK_CT_PRODUCT_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID) REFERENCES CT_EQUIPMENT (EQUIPMENT_ID),
    CONSTRAINT CK_CT_PRODUCT_FEE CHECK (MONTHLY_FEE > 0),
    CONSTRAINT CK_CT_PRODUCT_MONTHS CHECK (CONTRACT_MONTHS >= 1)
);

-- 3-4. 계약
CREATE TABLE CT_CONTRACT (
    CONTRACT_ID         NUMBER         NOT NULL,
    CONTRACT_NO         VARCHAR2(50)   NOT NULL,
    CUSTOMER_ID         NUMBER         NOT NULL,
    PRODUCT_ID          NUMBER         NOT NULL,
    MONTHLY_FEE         NUMBER         NOT NULL,
    START_DATE          DATE           NOT NULL,
    END_DATE            DATE           NOT NULL,
    INSTALL_ADDRESS     VARCHAR2(500)  NOT NULL,
    CONTRACT_STATUS     VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
    SUSPENDED_AT        TIMESTAMP(0),
    SUSPEND_REASON      VARCHAR2(1000),
    RESUMED_AT          TIMESTAMP(0),
    TERMINATED_AT       TIMESTAMP(0),
    TERMINATE_REASON    VARCHAR2(1000),
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CT_CONTRACT PRIMARY KEY (CONTRACT_ID),
    CONSTRAINT UK_CT_CONTRACT_NO UNIQUE (CONTRACT_NO),
    CONSTRAINT FK_CT_CONTRACT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CT_CUSTOMER (CUSTOMER_ID),
    CONSTRAINT FK_CT_CONTRACT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES CT_PRODUCT (PRODUCT_ID),
    CONSTRAINT CK_CT_CONTRACT_STATUS CHECK (CONTRACT_STATUS IN ('ACTIVE', 'SUSPENDED', 'TERMINATED')),
    CONSTRAINT CK_CT_CONTRACT_PERIOD CHECK (END_DATE > START_DATE)
);

-- 3-5. 기사
CREATE TABLE CT_ENGINEER (
    ENGINEER_ID         NUMBER         NOT NULL,
    ENGINEER_CODE       VARCHAR2(20)   NOT NULL,
    ENGINEER_NAME       VARCHAR2(100)  NOT NULL,
    ENGINEER_TYPE       VARCHAR2(20)   DEFAULT 'INTERNAL' NOT NULL,
    PHONE               VARCHAR2(20)   NOT NULL,
    EMAIL               VARCHAR2(254),
    AREA                VARCHAR2(100),
    USE_YN              VARCHAR2(1)        DEFAULT 'Y' NOT NULL,
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CT_ENGINEER PRIMARY KEY (ENGINEER_ID),
    CONSTRAINT UK_CT_ENGINEER_CODE UNIQUE (ENGINEER_CODE),
    CONSTRAINT CK_CT_ENGINEER_TYPE CHECK (ENGINEER_TYPE IN ('INTERNAL', 'EXTERNAL'))
);

-- 3-6. 방문 이력
CREATE TABLE CT_VISIT (
    VISIT_ID            NUMBER         NOT NULL,
    CONTRACT_ID         NUMBER         NOT NULL,
    ENGINEER_ID         NUMBER         NOT NULL,
    VISIT_TYPE          VARCHAR2(20)   NOT NULL,
    SCHEDULED_DATE      DATE           NOT NULL,
    COMPLETED_DATE      DATE,
    VISIT_STATUS        VARCHAR2(20)   DEFAULT 'SCHEDULED' NOT NULL,
    CANCEL_REASON       VARCHAR2(1000),
    MEMO                VARCHAR2(1000),
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_CT_VISIT PRIMARY KEY (VISIT_ID),
    CONSTRAINT FK_CT_VISIT_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CT_CONTRACT (CONTRACT_ID),
    CONSTRAINT FK_CT_VISIT_ENGINEER FOREIGN KEY (ENGINEER_ID) REFERENCES CT_ENGINEER (ENGINEER_ID),
    CONSTRAINT CK_CT_VISIT_TYPE CHECK (VISIT_TYPE IN ('INSTALL', 'CHECK', 'COLLECT')),
    CONSTRAINT CK_CT_VISIT_STATUS CHECK (VISIT_STATUS IN ('SCHEDULED', 'COMPLETED', 'CANCELLED'))
);

-- ============================================================
-- 4. 청구/수납 (BL_*) 테이블
-- ============================================================

-- 4-1. 배치 실행 이력 (BL_BILLING 의 FK 대상 — 먼저 생성)
CREATE TABLE BL_BATCH_LOG (
    BATCH_LOG_ID        NUMBER         NOT NULL,
    BATCH_TYPE          VARCHAR2(50)   NOT NULL,
    BILLING_MONTH       VARCHAR2(7),
    BATCH_STATUS        VARCHAR2(20)   DEFAULT 'RUNNING' NOT NULL,
    TARGET_COUNT        NUMBER         DEFAULT 0 NOT NULL,
    PROCESS_COUNT       NUMBER         DEFAULT 0 NOT NULL,
    SUCCESS_COUNT       NUMBER         DEFAULT 0 NOT NULL,
    FAIL_COUNT          NUMBER         DEFAULT 0 NOT NULL,
    DURATION_MS         NUMBER,
    ERROR_MSG           VARCHAR2(2000),
    STARTED_AT          TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMPLETED_AT        TIMESTAMP(0),
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_BL_BATCH_LOG PRIMARY KEY (BATCH_LOG_ID),
    CONSTRAINT UK_BL_BATCH_LOG UNIQUE (BATCH_TYPE, BILLING_MONTH),
    CONSTRAINT CK_BL_BATCH_LOG_STATUS CHECK (BATCH_STATUS IN ('RUNNING', 'COMPLETED', 'FAILED')),
    CONSTRAINT CK_BL_BATCH_LOG_TYPE CHECK (BATCH_TYPE IN ('BILLING_CREATE', 'OVERDUE_UPDATE'))
);

-- 4-2. 청구
CREATE TABLE BL_BILLING (
    BILLING_ID          NUMBER         NOT NULL,
    BILLING_NO          VARCHAR2(50)   NOT NULL,
    CONTRACT_ID         NUMBER         NOT NULL,
    CUSTOMER_ID         NUMBER         NOT NULL,
    BATCH_LOG_ID        NUMBER,
    BILLING_MONTH       VARCHAR2(7)    NOT NULL,
    BILLING_AMOUNT      NUMBER         NOT NULL,
    ISSUE_DATE          DATE           NOT NULL,
    DUE_DATE            DATE           NOT NULL,
    BILLING_STATUS      VARCHAR2(20)   DEFAULT 'UNPAID' NOT NULL,
    PAID_AT             TIMESTAMP(0),
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_BL_BILLING PRIMARY KEY (BILLING_ID),
    CONSTRAINT UK_BL_BILLING_CONTRACT_MONTH UNIQUE (CONTRACT_ID, BILLING_MONTH),
    CONSTRAINT UK_BL_BILLING_NO UNIQUE (BILLING_NO),
    CONSTRAINT FK_BL_BILLING_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CT_CONTRACT (CONTRACT_ID),
    CONSTRAINT FK_BL_BILLING_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CT_CUSTOMER (CUSTOMER_ID),
    CONSTRAINT FK_BL_BILLING_BATCH FOREIGN KEY (BATCH_LOG_ID) REFERENCES BL_BATCH_LOG (BATCH_LOG_ID),
    CONSTRAINT CK_BL_BILLING_STATUS CHECK (BILLING_STATUS IN ('UNPAID', 'OVERDUE', 'PAID', 'CANCELLED')),
    CONSTRAINT CK_BL_BILLING_AMOUNT CHECK (BILLING_AMOUNT > 0)
);

-- 4-3. 수납
CREATE TABLE BL_PAYMENT (
    PAYMENT_ID          NUMBER         NOT NULL,
    PAYMENT_NO          VARCHAR2(50)   NOT NULL,
    BILLING_ID          NUMBER         NOT NULL,
    CUSTOMER_ID         NUMBER         NOT NULL,
    PAYMENT_AMOUNT      NUMBER         NOT NULL,
    PAYMENT_METHOD      VARCHAR2(20)   NOT NULL,
    PAYMENT_DATE        DATE           NOT NULL,
    PAYMENT_STATUS      VARCHAR2(20)   DEFAULT 'COMPLETED' NOT NULL,
    CANCELLED_AT        TIMESTAMP(0),
    CANCEL_REASON       VARCHAR2(1000),
    TOSS_ORDER_ID       VARCHAR2(200),
    TOSS_PAYMENT_KEY    VARCHAR2(200),
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_BL_PAYMENT PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT UK_BL_PAYMENT_NO UNIQUE (PAYMENT_NO),
    CONSTRAINT UK_BL_PAYMENT_TOSS UNIQUE (TOSS_ORDER_ID),
    CONSTRAINT FK_BL_PAYMENT_BILLING FOREIGN KEY (BILLING_ID) REFERENCES BL_BILLING (BILLING_ID),
    CONSTRAINT FK_BL_PAYMENT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CT_CUSTOMER (CUSTOMER_ID),
    CONSTRAINT CK_BL_PAYMENT_METHOD CHECK (PAYMENT_METHOD IN ('CARD', 'BANK', 'CASH', 'TOSS')),
    CONSTRAINT CK_BL_PAYMENT_STATUS CHECK (PAYMENT_STATUS IN ('COMPLETED', 'CANCELLED', 'REFUNDED')),
    CONSTRAINT CK_BL_PAYMENT_AMOUNT CHECK (PAYMENT_AMOUNT > 0)
);

-- 4-4. 연체
CREATE TABLE BL_OVERDUE (
    OVERDUE_ID          NUMBER         NOT NULL,
    BILLING_ID          NUMBER         NOT NULL,
    CUSTOMER_ID         NUMBER         NOT NULL,
    OVERDUE_AMOUNT      NUMBER         NOT NULL,
    OVERDUE_DAYS        NUMBER         NOT NULL,
    RESOLVED_AT         TIMESTAMP(0),
    RESOLVE_REASON      VARCHAR2(1000),
    WRK_RMK             VARCHAR2(100),
    FIRS_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FIRS_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FIRS_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FIRS_REG_IP         VARCHAR2(50)   NOT NULL,
    FINA_REG_PGM_ID     VARCHAR2(50)   NOT NULL,
    FINA_REG_DTS        TIMESTAMP(0)   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FINA_REG_USER_ID    VARCHAR2(20)   NOT NULL,
    FINA_REG_IP         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_BL_OVERDUE PRIMARY KEY (OVERDUE_ID),
    CONSTRAINT UK_BL_OVERDUE_BILLING UNIQUE (BILLING_ID),
    CONSTRAINT FK_BL_OVERDUE_BILLING FOREIGN KEY (BILLING_ID) REFERENCES BL_BILLING (BILLING_ID),
    CONSTRAINT FK_BL_OVERDUE_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CT_CUSTOMER (CUSTOMER_ID)
);

-- ============================================================
-- 완료 메시지
-- ============================================================
BEGIN
    DBMS_OUTPUT.PUT_LINE('rental-crm schema created: 17 tables, 17 sequences');
END;
/
