-- ============================================================
-- rental-crm 공통코드 초기 시드 데이터
-- CM_CODE_GROUP / CM_CODE — 04 기능명세서 §0-1 기준
--
-- 모든 INSERT 에 감사 9컬럼 채움 (시드 데이터의 등록자: SYSTEM)
-- ============================================================

ALTER SESSION SET CURRENT_SCHEMA = rental;

-- ============================================================
-- 1. 코드 그룹
-- ============================================================

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('EQUIPMENT_TYPE',  '장비유형',     '렌탈 장비의 분류',      'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('CONTRACT_STATUS', '계약상태',     '계약의 진행 상태',      'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('BILLING_STATUS',  '청구상태',     '청구의 수납 상태',      'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('PAYMENT_METHOD',  '수납방법',     '수납 결제 수단',        'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('VISIT_TYPE',      '방문유형',     '기사 방문의 목적',      'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('NOTIFICATION_TYPE','알림유형',    'Kafka Consumer 알림 유형','Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- ============================================================
-- 2. 코드값
-- ============================================================

-- 장비유형
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'EQUIPMENT_TYPE', 'AC',       '가전',     10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'EQUIPMENT_TYPE', 'FURNITURE','가구',     20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'EQUIPMENT_TYPE', 'IT',       'IT장비',   30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'EQUIPMENT_TYPE', 'MEDICAL',  '의료장비', 40, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 계약상태
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'CONTRACT_STATUS', 'ACTIVE',     '정상',     10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'CONTRACT_STATUS', 'SUSPENDED',  '일시정지', 20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'CONTRACT_STATUS', 'TERMINATED', '해지',     30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 청구상태
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'BILLING_STATUS', 'UNPAID',    '미납',     10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'BILLING_STATUS', 'OVERDUE',   '연체',     20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'BILLING_STATUS', 'PAID',      '수납완료', 30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'BILLING_STATUS', 'CANCELLED', '취소',     40, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 수납방법
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'PAYMENT_METHOD', 'CARD', '카드',         10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'PAYMENT_METHOD', 'BANK', '계좌이체',     20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'PAYMENT_METHOD', 'CASH', '현금',         30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'PAYMENT_METHOD', 'TOSS', '토스페이먼츠', 40, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 방문유형
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'VISIT_TYPE', 'INSTALL', '설치', 10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'VISIT_TYPE', 'CHECK',   '점검', 20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'VISIT_TYPE', 'COLLECT', '수거', 30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 알림 유형
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'NOTIFICATION_TYPE', 'BILLING_CREATED',   '청구 생성',   10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'NOTIFICATION_TYPE', 'PAYMENT_COMPLETED', '수납 완료',   20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'NOTIFICATION_TYPE', 'PAYMENT_OVERDUE',   '연체 발생',   30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'NOTIFICATION_TYPE', 'VISIT_ASSIGNED',    '방문 배정',   40, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- ============================================================
-- 3. 기본 역할 (CM_ROLE)
-- ============================================================

INSERT INTO CM_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_ROLE.NEXTVAL, 'SUPER_ADMIN', '최고관리자', '모든 메뉴 접근 권한. 삭제/수정 불가', 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_ROLE.NEXTVAL, 'ADMIN', '관리자', '일반 관리자', 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_ROLE.NEXTVAL, 'VIEWER', '조회전용', '읽기 전용 권한', 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

COMMIT;

-- ============================================================
-- 완료 메시지
-- ============================================================
BEGIN
    DBMS_OUTPUT.PUT_LINE('rental-crm seed data inserted: 6 groups, 24 codes, 3 roles');
END;
/
