-- ============================================================
-- rental-crm 공통코드 초기 시드 데이터
-- CM_CODE_GROUP / CM_CODE — 04 기능명세서 §0-1 기준
--
-- 모든 INSERT 에 감사 9컬럼 채움 (시드 데이터의 등록자: SYSTEM)
-- ============================================================

ALTER SESSION SET CURRENT_SCHEMA = rental;

-- ============================================================
-- 1. 코드 그룹
-- ============================================================

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('EQUIPMENT_TYPE',  '장비유형',     '렌탈 장비의 분류',      'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('CONTRACT_STATUS', '계약상태',     '계약의 진행 상태',      'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('BILLING_STATUS',  '청구상태',     '청구의 수납 상태',      'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('PAYMENT_METHOD',  '수납방법',     '수납 결제 수단',        'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('VISIT_TYPE',      '방문유형',     '기사 방문의 목적',      'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_CODE_GROUP (GROUP_CODE, GROUP_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
('NOTIFICATION_TYPE','알림유형',    'Kafka Consumer 알림 유형','Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- ============================================================
-- 2. 코드값
-- ============================================================

-- 장비유형
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'EQUIPMENT_TYPE', 'AC',       '가전',     10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'EQUIPMENT_TYPE', 'FURNITURE','가구',     20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'EQUIPMENT_TYPE', 'IT',       'IT장비',   30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'EQUIPMENT_TYPE', 'MEDICAL',  '의료장비', 40, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 계약상태
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'CONTRACT_STATUS', 'ACTIVE',     '정상',     10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'CONTRACT_STATUS', 'SUSPENDED',  '일시정지', 20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'CONTRACT_STATUS', 'TERMINATED', '해지',     30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 청구상태
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'BILLING_STATUS', 'UNPAID',    '미납',     10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'BILLING_STATUS', 'OVERDUE',   '연체',     20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'BILLING_STATUS', 'PAID',      '수납완료', 30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'BILLING_STATUS', 'CANCELLED', '취소',     40, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 수납방법
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'PAYMENT_METHOD', 'CARD', '카드',         10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'PAYMENT_METHOD', 'BANK', '계좌이체',     20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'PAYMENT_METHOD', 'CASH', '현금',         30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'PAYMENT_METHOD', 'TOSS', '토스페이먼츠', 40, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 방문유형
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'VISIT_TYPE', 'INSTALL', '설치', 10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'VISIT_TYPE', 'CHECK',   '점검', 20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'VISIT_TYPE', 'COLLECT', '수거', 30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 알림 유형
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'NOTIFICATION_TYPE', 'BILLING_CREATED',   '청구 생성',   10, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'NOTIFICATION_TYPE', 'PAYMENT_COMPLETED', '수납 완료',   20, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'NOTIFICATION_TYPE', 'PAYMENT_OVERDUE',   '연체 발생',   30, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_CODE (CODE_ID, GROUP_CODE, CODE_VALUE, CODE_NAME, SORT_ORDER, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_CODE.NEXTVAL, 'NOTIFICATION_TYPE', 'VISIT_ASSIGNED',    '방문 배정',   40, 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- ============================================================
-- 3. 기본 역할 (CM_ROLE)
-- ============================================================

INSERT INTO CM_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_ROLE.NEXTVAL, 'SUPER_ADMIN', '최고관리자', '모든 메뉴 접근 권한. 삭제/수정 불가', 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_ROLE.NEXTVAL, 'ADMIN', '관리자', '일반 관리자', 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

INSERT INTO CM_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, USE_YN, WRK_RMK, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES
(SEQ_CM_ROLE.NEXTVAL, 'VIEWER', '조회전용', '읽기 전용 권한', 'Y', NULL, 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

COMMIT;

-- ============================================================
-- 4. 메뉴 트리 (CM_MENU) — 23 행 (GROUP 7 + LEAF 16)
-- ADR-008/009 — 메뉴 진입권은 *_VIEW 권한으로 판정 (단일 source of truth)
-- ============================================================

DECLARE
    -- GROUP 메뉴 IDs (PARENT_MENU_ID 참조용)
    v_grp_sys       NUMBER;
    v_grp_member    NUMBER;
    v_grp_equip     NUMBER;
    v_grp_contract  NUMBER;
    v_grp_engineer  NUMBER;
    v_grp_billing   NUMBER;
    v_grp_report    NUMBER;
BEGIN
    -- GROUP 메뉴 (7개) — depth=1, MENU_URL=NULL, ICON 있음
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, NULL, 1, '시스템관리',   'GROUP', NULL, 'ti ti-settings',       10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1') RETURNING MENU_ID INTO v_grp_sys;
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, NULL, 1, '회원관리',     'GROUP', NULL, 'ti ti-users',          20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1') RETURNING MENU_ID INTO v_grp_member;
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, NULL, 1, '장비/상품',    'GROUP', NULL, 'ti ti-device-desktop', 30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1') RETURNING MENU_ID INTO v_grp_equip;
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, NULL, 1, '계약관리',     'GROUP', NULL, 'ti ti-file-text',      40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1') RETURNING MENU_ID INTO v_grp_contract;
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, NULL, 1, '기사/방문',    'GROUP', NULL, 'ti ti-tools',          50, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1') RETURNING MENU_ID INTO v_grp_engineer;
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, NULL, 1, '청구/수납',    'GROUP', NULL, 'ti ti-credit-card',    60, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1') RETURNING MENU_ID INTO v_grp_billing;
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, NULL, 1, '통계/리포트',  'GROUP', NULL, 'ti ti-chart-bar',      70, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1') RETURNING MENU_ID INTO v_grp_report;

    -- LEAF — 시스템관리 (4)
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_sys,      2, '공통코드',     'LEAF', '/admin/codes',           NULL, 10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_sys,      2, '메뉴관리',     'LEAF', '/admin/menus',           NULL, 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_sys,      2, '권한관리',     'LEAF', '/admin/roles',           NULL, 30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_sys,      2, '관리자관리',   'LEAF', '/admin/users',           NULL, 40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

    -- LEAF — 회원관리 (1)
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_member,   2, '고객',         'LEAF', '/admin/customers',       NULL, 10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

    -- LEAF — 장비/상품 (2)
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_equip,    2, '장비',         'LEAF', '/admin/equipments',      NULL, 10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_equip,    2, '상품',         'LEAF', '/admin/products',        NULL, 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

    -- LEAF — 계약관리 (1)
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_contract, 2, '계약',         'LEAF', '/admin/contracts',       NULL, 10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

    -- LEAF — 기사/방문 (2)
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_engineer, 2, '기사',         'LEAF', '/admin/engineers',       NULL, 10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_engineer, 2, '방문이력',     'LEAF', '/admin/visits',          NULL, 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

    -- LEAF — 청구/수납 (4)
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_billing,  2, '청구',         'LEAF', '/admin/billings',        NULL, 10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_billing,  2, '수납',         'LEAF', '/admin/payments',        NULL, 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_billing,  2, '연체',         'LEAF', '/admin/overdues',        NULL, 30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_billing,  2, '배치이력',     'LEAF', '/admin/batches',         NULL, 40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

    -- LEAF — 통계/리포트 (1)
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, v_grp_report,   2, '미납현황',     'LEAF', '/admin/reports/overdue', NULL, 10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

    -- 단독 LEAF (2) — depth=1, parent=NULL
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, NULL,           1, '대시보드',     'LEAF', '/admin/dashboard',       'ti ti-dashboard', 80, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
    INSERT INTO CM_MENU (MENU_ID, PARENT_MENU_ID, MENU_DEPTH, MENU_NAME, MENU_TYPE, MENU_URL, ICON_CLASS, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES (SEQ_CM_MENU.NEXTVAL, NULL,           1, '알림',         'LEAF', '/admin/notifications',   'ti ti-bell',      90, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

    COMMIT;
END;
/

-- ============================================================
-- 5. 권한 키 (CM_AUTH) — 57 행
-- MENU_ID 는 LEAF 메뉴의 MENU_URL 로 조회 (글로벌 권한은 추후 NULL 가능)
-- ============================================================

-- 시스템관리 그룹 (20)
-- 공통코드 (4)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CODE_VIEW',   '공통코드 조회', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/codes'), 'VIEW',   10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CODE_CREATE', '공통코드 등록', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/codes'), 'CREATE', 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CODE_UPDATE', '공통코드 수정', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/codes'), 'UPDATE', 30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CODE_DELETE', '공통코드 삭제', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/codes'), 'DELETE', 40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 메뉴관리 (4)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('MENU_VIEW',   '메뉴 조회', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/menus'), 'VIEW',   10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('MENU_CREATE', '메뉴 등록', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/menus'), 'CREATE', 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('MENU_UPDATE', '메뉴 수정', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/menus'), 'UPDATE', 30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('MENU_DELETE', '메뉴 삭제', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/menus'), 'DELETE', 40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 권한관리 (6)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('ROLE_VIEW',    '역할 조회',          (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/roles'), 'VIEW',   10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('ROLE_CREATE',  '역할 등록',          (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/roles'), 'CREATE', 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('ROLE_UPDATE',  '역할 수정',          (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/roles'), 'UPDATE', 30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('ROLE_DELETE',  '역할 삭제',          (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/roles'), 'DELETE', 40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('AUTH_VIEW',    '권한 키 마스터 조회', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/roles'), 'VIEW',   50, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('AUTH_ASSIGN',  '역할에 권한 매핑',    (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/roles'), 'UPDATE', 60, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 관리자관리 (6)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('USER_VIEW',           '관리자 조회',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/users'), 'VIEW',    10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('USER_CREATE',         '관리자 등록',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/users'), 'CREATE',  20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('USER_UPDATE',         '관리자 수정',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/users'), 'UPDATE',  30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('USER_DELETE',         '관리자 비활성화', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/users'), 'DELETE',  40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('USER_UNLOCK',         '관리자 잠금해제', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/users'), 'EXECUTE', 50, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('USER_RESET_PASSWORD', '비밀번호 재설정', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/users'), 'EXECUTE', 60, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 회원관리: 고객 (5)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CUSTOMER_VIEW',   '고객 조회',        (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/customers'), 'VIEW',    10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CUSTOMER_CREATE', '고객 등록',        (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/customers'), 'CREATE',  20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CUSTOMER_UPDATE', '고객 수정',        (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/customers'), 'UPDATE',  30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CUSTOMER_DELETE', '고객 비활성화',    (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/customers'), 'DELETE',  40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CUSTOMER_EXPORT', '고객 엑셀 다운로드', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/customers'), 'EXECUTE', 50, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 장비/상품: 장비 (4)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('EQUIPMENT_VIEW',   '장비 조회',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/equipments'), 'VIEW',   10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('EQUIPMENT_CREATE', '장비 등록',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/equipments'), 'CREATE', 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('EQUIPMENT_UPDATE', '장비 수정',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/equipments'), 'UPDATE', 30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('EQUIPMENT_DELETE', '장비 비활성화', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/equipments'), 'DELETE', 40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 장비/상품: 상품 (4)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('PRODUCT_VIEW',   '상품 조회',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/products'), 'VIEW',   10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('PRODUCT_CREATE', '상품 등록',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/products'), 'CREATE', 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('PRODUCT_UPDATE', '상품 수정',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/products'), 'UPDATE', 30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('PRODUCT_DELETE', '상품 비활성화', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/products'), 'DELETE', 40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 계약 (6)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CONTRACT_VIEW',      '계약 조회',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/contracts'), 'VIEW',    10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CONTRACT_CREATE',    '계약 등록',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/contracts'), 'CREATE',  20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CONTRACT_UPDATE',    '계약 수정',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/contracts'), 'UPDATE',  30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CONTRACT_DELETE',    '계약 삭제',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/contracts'), 'DELETE',  40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CONTRACT_SUSPEND',   '계약 일시정지', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/contracts'), 'EXECUTE', 50, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('CONTRACT_TERMINATE', '계약 해지',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/contracts'), 'EXECUTE', 60, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 기사/방문: 기사 (4)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('ENGINEER_VIEW',   '기사 조회',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/engineers'), 'VIEW',   10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('ENGINEER_CREATE', '기사 등록',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/engineers'), 'CREATE', 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('ENGINEER_UPDATE', '기사 수정',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/engineers'), 'UPDATE', 30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('ENGINEER_DELETE', '기사 비활성화', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/engineers'), 'DELETE', 40, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 기사/방문: 방문이력 (3)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('VISIT_VIEW',     '방문이력 조회', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/visits'), 'VIEW',    10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('VISIT_ASSIGN',   '방문 배정',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/visits'), 'EXECUTE', 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('VISIT_COMPLETE', '방문 완료',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/visits'), 'EXECUTE', 30, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 청구/수납: 청구 (2)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('BILLING_VIEW',      '청구 조회',          (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/billings'), 'VIEW',    10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('BILLING_BATCH_RUN', '월 청구 배치 실행', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/billings'), 'EXECUTE', 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 청구/수납: 수납 (2)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('PAYMENT_VIEW',   '수납 조회', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/payments'), 'VIEW',   10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('PAYMENT_CREATE', '수납 처리', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/payments'), 'CREATE', 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 청구/수납: 연체 (2)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('OVERDUE_VIEW',    '연체 조회',     (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/overdues'), 'VIEW',    10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('OVERDUE_RELEASE', '연체 수동해제', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/overdues'), 'EXECUTE', 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 청구/수납: 배치이력 (1)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('BATCH_LOG_VIEW', '배치 실행 이력 조회', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/batches'), 'VIEW', 10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 통계/리포트: 미납현황 (2)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('OVERDUE_REPORT_VIEW',   '미납 현황 조회', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/reports/overdue'), 'VIEW',    10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('OVERDUE_REPORT_EXPORT', '미납 현황 엑셀', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/reports/overdue'), 'EXECUTE', 20, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 대시보드 (1)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('DASHBOARD_VIEW', '대시보드 조회', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/dashboard'), 'VIEW', 10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

-- 알림 (1)
INSERT INTO CM_AUTH (AUTH_CODE, AUTH_NAME, MENU_ID, AUTH_TYPE, SORT_ORDER, USE_YN, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP) VALUES ('NOTIFICATION_VIEW', '알림 조회', (SELECT MENU_ID FROM CM_MENU WHERE MENU_URL='/admin/notifications'), 'VIEW', 10, 'Y', 'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1');

COMMIT;

-- ============================================================
-- 6. 역할-권한 매핑 (CM_ROLE_AUTH) — 107 행
-- SUPER_ADMIN 57 + ADMIN 37 + VIEWER 13
-- ============================================================

-- SUPER_ADMIN: 모든 57 권한
INSERT INTO CM_ROLE_AUTH (ROLE_AUTH_ID, ROLE_ID, AUTH_CODE, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP)
SELECT SEQ_CM_ROLE_AUTH.NEXTVAL,
       (SELECT ROLE_ID FROM CM_ROLE WHERE ROLE_CODE='SUPER_ADMIN'),
       AUTH_CODE,
       'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1'
  FROM CM_AUTH;

-- ADMIN: 시스템관리 그룹 제외 (37 권한)
INSERT INTO CM_ROLE_AUTH (ROLE_AUTH_ID, ROLE_ID, AUTH_CODE, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP)
SELECT SEQ_CM_ROLE_AUTH.NEXTVAL,
       (SELECT ROLE_ID FROM CM_ROLE WHERE ROLE_CODE='ADMIN'),
       AUTH_CODE,
       'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1'
  FROM CM_AUTH
 WHERE AUTH_CODE NOT LIKE 'CODE\_%' ESCAPE '\'
   AND AUTH_CODE NOT LIKE 'MENU\_%' ESCAPE '\'
   AND AUTH_CODE NOT LIKE 'ROLE\_%' ESCAPE '\'
   AND AUTH_CODE NOT LIKE 'AUTH\_%' ESCAPE '\'
   AND AUTH_CODE NOT LIKE 'USER\_%' ESCAPE '\';

-- VIEWER: 일반 도메인 *_VIEW 만 (13 권한 — 시스템관리 *_VIEW 제외)
INSERT INTO CM_ROLE_AUTH (ROLE_AUTH_ID, ROLE_ID, AUTH_CODE, FIRS_REG_PGM_ID, FIRS_REG_USER_ID, FIRS_REG_IP, FINA_REG_PGM_ID, FINA_REG_USER_ID, FINA_REG_IP)
SELECT SEQ_CM_ROLE_AUTH.NEXTVAL,
       (SELECT ROLE_ID FROM CM_ROLE WHERE ROLE_CODE='VIEWER'),
       AUTH_CODE,
       'SEED', 'SYSTEM', '127.0.0.1', 'SEED', 'SYSTEM', '127.0.0.1'
  FROM CM_AUTH
 WHERE AUTH_TYPE = 'VIEW'
   AND AUTH_CODE NOT IN ('CODE_VIEW', 'MENU_VIEW', 'ROLE_VIEW', 'AUTH_VIEW', 'USER_VIEW');

COMMIT;

-- ============================================================
-- 완료 메시지
-- ============================================================
BEGIN
    DBMS_OUTPUT.PUT_LINE('rental-crm seed data inserted: 6 groups, 24 codes, 3 roles, 23 menus, 57 auths, 107 role_auths');
END;
/
